# Generated by Django 4.2.14 on 2024-07-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('score', models.IntegerField(default=0)),
                ('pre_approved_at', models.DateTimeField(null=True)),
                ('estado', models.SmallIntegerField(choices=[(1, 1), (2, 2)], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
