# Generated by Django 4.2.14 on 2024-07-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='estado',
            new_name='status',
        ),
    ]
