# Generated by Django 4.2.14 on 2024-07-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_estado_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pre_approved_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
